<?php

/**
 * @license         Berkeley Software Distribution License (BSD-License 2) http://www.opensource.org/licenses/bsd-license.php
 * @author          Roemer Bakker
 * @copyright       Complexity Software
 */

namespace SpryngPaymentsApiPhp\Object;

/**
 * Class Spryng_Payments_Api_Object_Subscription
 * @package Spryng_PaymentsApiPhp\Object
 */
class Subscription
{
    /**
     * Generated by the gateway when the subscription is created.
     *
     * @var string
     */
    public $_id;

    /**
     * Payment account.
     *
     * @var Spryng_Payments_Api_Object_Account
     */
    public $account;

    /**
     * Amount is charged without a decimal place e.g. $1.5 = 150. Currencies can have different decimals/exponentials,
     * see Currencies Section for more details.
     *
     * @var integer
     */
    public $amount;

    /**
     * One of day, week, month or year. The frequency with which a subscription should be billed.
     *
     * @var string
     */
    public $interval;

    /**
     * A metadata field available for storing additional information in the subscription object.
     *
     * @var string
     */
    public $merchant_reference;

    /**
     * An Object representing the card
     *
     * @var Spryng_Payments_Api_Object_Card
     */
    public $card;

    /**
     * An Object representing the customer
     *
     * @var Spryng_Payments_Api_Object_Customer
     */
    public $customer;

    /**
     * The frequency of months a subscription is to occur e.g. value is 1 for every month, 3 for every three months
     * or 6 for every 6 months. Weekly subscriptions are not possible. We suggest not to use yearly subscriptions due
     * to the effect it will have on your success rates.
     *
     * @var integer
     */
    public $frequency;

    /**
     * The day the subscription is to commence in format dd/mm/yyyy.
     *
     * @var Date
     */
    public $start_date;

    /**
     * The last day of the subscription in format dd/mm/yyyy.
     *
     * @var Date
     */
    public $end_date;
}